<?php

/**
 * Arabic alt text for the media library, keyed by the English verified
 * description the import recorded for each photograph.
 *
 * Why this file exists: the library arrived with English descriptions
 * from a bulk analysis pass, and the site is Arabic RTL. Alt text in the
 * wrong language is useless to an Arabic screen-reader user and worthless
 * for Arabic search, so every recurring description is translated here
 * once, by hand, and reused wherever it appears.
 *
 * Two rules bind every line below:
 *  - Alt describes the photograph and nothing else. No brand name, no
 *    "أفضل", no claim about a result. The library's own suggested alt
 *    column was discarded for exactly that reason: it opened with a
 *    marketing sentence.
 *  - Nothing is added that the description did not record. Where the
 *    English is vague ("associated with cleaning work"), the Arabic stays
 *    equally careful rather than inventing a scene.
 *
 * An editor may overwrite any alt text in the panel; this is only the
 * starting value for photos that had none.
 *
 * @return array<string, string>
 */

return [
    'worker cleaning aluminium facade elements' => 'عامل ينظف عناصر ألمنيوم في واجهة مبنى',
    'workers cleaning villa swimming pool' => 'عمال ينظفون مسبح فيلا',
    'worker cleaning washroom floors, counters, sinks and wall surfaces' => 'عامل ينظف أرضيات دورة مياه ومغاسلها وكاونترها وجدرانها',
    'workers cleaning bathroom, corridor and interior floor surfaces' => 'عمال ينظفون حمامًا وممرًا وأرضيات داخلية',
    'worker cleaning bathroom vanity and sink' => 'عامل ينظف مغسلة حمام وكاونترها',
    'worker cleaning bathroom vanity and cabinet surfaces' => 'عامل ينظف مغسلة حمام وأسطح خزائنها',
    'worker detail-cleaning wall panels, skirting or decorative surfaces' => 'عامل ينظف ألواحًا جدارية وقواعد حائط وأسطحًا زخرفية بالتفصيل',
    'worker cleaning or extracting dirt from residential interior flooring' => 'عامل ينظف أرضية داخلية سكنية باستخلاص الأوساخ',
    'worker cleaning high ceiling, wall or overhead interior surfaces using ladder or extension tool' => 'عامل ينظف سقفًا وجدارًا مرتفعًا بسلم وأداة تلسكوبية',
    'worker cleaning high ceiling, wall or overhead interior surfaces using ladder or extension tools' => 'عامل ينظف سقفًا وجدارًا مرتفعًا بسلم وأدوات تلسكوبية',
    'worker cleaning large decorative chandelier' => 'عامل ينظف ثريا زخرفية كبيرة',
    'clean polished floor near elevator doors explicitly labeled after cleaning' => 'أرضية لامعة نظيفة أمام أبواب مصعد — لقطة موسومة بعد التنظيف',
    'washroom stall and floor explicitly labeled before cleaning' => 'قاطع دورة مياه وأرضيتها — لقطة موسومة قبل التنظيف',
    'crew cleaning high interior architectural elements using elevated access' => 'فريق ينظف عناصر معمارية داخلية مرتفعة بمعدات وصول',
    'cleaning team washing and detailing a commercial corridor floor' => 'فريق تنظيف يغسل أرضية ممر تجاري ويفصّلها',
    'worker wiping corridor walls and handrails in the same scene as another frame' => 'عامل يمسح جدران ممر ودرابزينه',
    'worker wiping lower wall and skirting surfaces' => 'عامل يمسح أسفل الجدار وقواعد الحائط',
    'interior floor cleaning near escalator' => 'تنظيف أرضية داخلية بجوار سلم كهربائي',
    'cleaning team washing and scrubbing a commercial parking floor' => 'فريق تنظيف يغسل ويفرك أرضية موقف سيارات تجاري',
    'worker cleaning sports facility floor and equipment' => 'عامل ينظف أرضية منشأة رياضية ومعداتها',
    'worker on a ladder cleaning high cabinet or wall surfaces' => 'عامل على سلم ينظف خزائن وأسطحًا جدارية مرتفعة',
    'worker cleaning polished public interior floor' => 'عامل ينظف أرضية لامعة في مساحة داخلية عامة',
    'workers cleaning polished floors, glass, counters, stairs and office interior surfaces' => 'عمال ينظفون أرضيات لامعة وزجاجًا وكاونترات ودرجًا في مكتب',
    'worker on ladder cleaning high interior surfaces' => 'عامل على سلم ينظف أسطحًا داخلية مرتفعة',
    'worker cleaning high interior wall or ceiling using access equipment' => 'عامل ينظف جدارًا أو سقفًا داخليًا مرتفعًا بمعدات وصول',
    'worker cleaning indoor commercial floor or carpeted area' => 'عامل ينظف أرضية تجارية داخلية أو منطقة مفروشة بالسجاد',
    'commercial facility exterior associated with cleaning operations' => 'واجهة خارجية لمنشأة تجارية ضمن أعمال تنظيف',
    'large covered venue or structure associated with exterior cleaning' => 'منشأة مغطاة كبيرة ضمن أعمال تنظيف خارجية',
    'workers cleaning office counters, glass, desks, floors and interior surfaces' => 'عمال ينظفون كاونترات مكتب وزجاجه ومكاتبه وأرضياته',
    'workers cleaning ground-level exterior glass panels' => 'عمال ينظفون ألواح زجاج خارجية على مستوى الأرض',
    'team cleaning large dark commercial floor' => 'فريق ينظف أرضية تجارية داكنة واسعة',
    'wet outdoor paving during exterior surface cleaning' => 'بلاط خارجي مبلل أثناء تنظيف الأسطح الخارجية',
    'workers cleaning large polished commercial floor' => 'عمال ينظفون أرضية تجارية لامعة واسعة',
    'large decorative chandelier or ceiling installation being cleaned' => 'ثريا زخرفية كبيرة أو تركيب سقفي أثناء تنظيفه',
    'workers cleaning tall glass facade using scaffold or powered access' => 'عمال ينظفون واجهة زجاجية مرتفعة بسقالة أو معدات وصول',
    'high-access facade cleaning across commercial building exteriors' => 'تنظيف واجهات مبانٍ تجارية من ارتفاع',
    'cleaning gym and sports equipment' => 'تنظيف صالة رياضية ومعداتها',
    'worker cleaning gym exercise machine' => 'عامل ينظف جهاز تمارين في صالة رياضية',
    'workers cleaning commercial kitchen or service counter area' => 'عمال ينظفون مطبخًا تجاريًا أو منطقة كاونتر خدمة',
    'workers deep-cleaning wall panels and interior surfaces' => 'عمال ينظفون ألواحًا جدارية وأسطحًا داخلية تنظيفًا عميقًا',
    'cleaned parking garage floor' => 'أرضية موقف سيارات مغطى بعد التنظيف',
    'clean finished interior with dark wood cabinetry documented during project' => 'مساحة داخلية مكتملة التشطيب بنجارة خشبية داكنة نظيفة',
    'clean empty room floor and wall finish documented after project work' => 'أرضية غرفة فارغة وتشطيب جدارها بعد انتهاء العمل',
    'workers deep cleaning bathroom surfaces' => 'عمال ينظفون أسطح حمام تنظيفًا عميقًا',
    'worker hand-cleaning a large stone or tile wall surface' => 'عامل ينظف جدارًا حجريًا أو مبلطًا واسعًا يدويًا',
    'worker performing detailed floor and surface cleaning in an ornate interior' => 'عامل ينظف أرضية وأسطحًا بالتفصيل في مساحة داخلية مزخرفة',
    'worker cleaning interior door or wall surface' => 'عامل ينظف بابًا داخليًا أو سطحًا جداريًا',
    'worker detail-cleaning floor edge beside a wall and window' => 'عامل ينظف حافة أرضية بجانب جدار ونافذة',
    'worker cleaning inside a dark kitchen drawer or cabinet' => 'عامل ينظف داخل درج أو خزانة مطبخ داكنة',
    'worker cleaning tall kitchen wall or cabinetry with extension tool' => 'عامل ينظف جدار مطبخ مرتفعًا أو خزائنه بأداة تلسكوبية',
    'worker cleaning or dusting indoor plant area' => 'عامل ينظف منطقة نباتات داخلية',
    'worker cleaning tall interior wall or cabinet panels' => 'عامل ينظف جدارًا داخليًا مرتفعًا أو ألواح خزائن',
    'worker detail-cleaning walls, cabinetry and upper interior surfaces' => 'عامل ينظف جدرانًا ونجارة وأسطحًا داخلية عليا بالتفصيل',
    'commercial building exterior associated with facade cleaning' => 'واجهة مبنى تجاري ضمن أعمال تنظيف الواجهات',
    'boom-lift crew cleaning a multi-storey commercial facade' => 'طاقم على رافعة سلة ينظف واجهة مبنى تجاري متعدد الطوابق',
    'commercial building exterior with signage' => 'واجهة مبنى تجاري تحمل لوحة اسم',
    'workers cleaning exterior floors, stairs, glass, walls and garden-side surfaces' => 'عمال ينظفون أرضيات ودرجًا وزجاجًا وجدرانًا خارجية جهة الحديقة',
    'multi-image cleaning detail collage' => 'مجموعة لقطات تفصيلية من أعمال التنظيف',
    'exterior cladding and facade cleaning using access equipment' => 'تنظيف كسوة وواجهة خارجية بمعدات وصول',
    'close view of modern blue facade panels prepared for cleaning' => 'لقطة قريبة لألواح واجهة زرقاء حديثة قبل تنظيفها',
    'rope-access or lift-assisted facade and high-level glass cleaning' => 'تنظيف واجهة وزجاج مرتفع بالحبال أو برافعة',
    'workers cleaning upper facade with access equipment' => 'عمال ينظفون الجزء العلوي من واجهة بمعدات وصول',
    'high-level exterior facade cleaning' => 'تنظيف واجهة خارجية على ارتفاع',
    'commercial building exterior documented in project context' => 'واجهة مبنى تجاري موثقة ضمن مشروع تنظيف',
    'cleaning work outside commercial building' => 'أعمال تنظيف خارج مبنى تجاري',
    'boom lift positioned at building entrance for facade cleaning' => 'رافعة سلة عند مدخل مبنى استعدادًا لتنظيف الواجهة',
    'clean commercial building exterior shown after service work' => 'واجهة مبنى تجاري نظيفة بعد تنفيذ الخدمة',
    'glass-clad building exterior documented as part of cleaning work' => 'واجهة مبنى مكسوة بالزجاج ضمن أعمال التنظيف',
    'high-access exterior cleaning work on building facade' => 'أعمال تنظيف خارجي على واجهة مبنى من ارتفاع',
    'team cleaning large outdoor paved area' => 'فريق ينظف مساحة خارجية مبلطة واسعة',
    'worker cleaning tall colored exterior wall' => 'عامل ينظف جدارًا خارجيًا ملوّنًا مرتفعًا',
    'labeled before-and-after views of exterior cladding and facade surfaces' => 'لقطات موسومة قبل وبعد لأسطح كسوة وواجهة خارجية',
    'team cleaning large exterior roof or paved surface' => 'فريق ينظف سطحًا خارجيًا واسعًا أو مساحة مبلطة',
    'boom lift cleaning shopping or commercial facade' => 'رافعة سلة أثناء تنظيف واجهة مركز تجاري',
    'workers cleaning exterior deck, wooden screens and garden-side surfaces' => 'عمال ينظفون ديكًا خارجيًا وشاشات خشبية وأسطحًا جهة الحديقة',
    'multi-storey building exterior associated with cleaning work' => 'واجهة مبنى متعدد الطوابق ضمن أعمال التنظيف',
    'boom lift cleaning stone and glass building facade' => 'رافعة سلة أثناء تنظيف واجهة مبنى حجرية وزجاجية',
    'workers cleaning tall residential windows using access equipment' => 'عمال ينظفون نوافذ سكنية مرتفعة بمعدات وصول',
    'large scaffold setup for facade cleaning' => 'سقالة كبيرة مركّبة لتنظيف واجهة',
    'modern commercial building exterior linked to cleaning work' => 'واجهة مبنى تجاري حديث ضمن أعمال التنظيف',
    'boom lift cleaning a glass facade from street level' => 'رافعة سلة تنظف واجهة زجاجية من مستوى الشارع',
    'boom truck cleaning upper facade of a modern building' => 'شاحنة رافعة تنظف أعلى واجهة مبنى حديث',
    'large building exterior associated with facade work' => 'واجهة مبنى كبير ضمن أعمال الواجهات',
    'worker cleaning exterior glass at height' => 'عامل ينظف زجاجًا خارجيًا على ارتفاع',
    'boom truck positioned for facade cleaning at a low-rise property' => 'شاحنة رافعة متمركزة لتنظيف واجهة مبنى منخفض',
    'boom-lift cleaning vehicles positioned outside a commercial site' => 'مركبات رافعة متمركزة خارج موقع تجاري لأعمال التنظيف',
    'boom lift positioned against a glass building facade' => 'رافعة سلة متمركزة أمام واجهة مبنى زجاجية',
    'boom lift cleaning vertical facade panels' => 'رافعة سلة تنظف ألواح واجهة رأسية',
    'high-rise facade cleaning from boom lift' => 'تنظيف واجهة مبنى مرتفع من رافعة سلة',
    'worker cleaning exterior wall or facade from scaffold' => 'عامل ينظف جدارًا أو واجهة خارجية من سقالة',
    'rope-access workers cleaning tall exterior facade' => 'فنيون بالحبال ينظفون واجهة خارجية مرتفعة',
    'boom lift reaching upper commercial facade' => 'رافعة سلة تصل إلى أعلى واجهة تجارية',
    'boom-lift crew cleaning upper glass facade panels' => 'طاقم على رافعة سلة ينظف ألواح زجاج علوية في واجهة',
    'boom lift cleaning high-rise facade' => 'رافعة سلة تنظف واجهة مبنى مرتفع',
    'workers cleaning large exterior glass facade' => 'عمال ينظفون واجهة زجاجية خارجية واسعة',
    'boom lift positioned for exterior facade cleaning at dusk' => 'رافعة سلة متمركزة لتنظيف واجهة خارجية عند الغروب',
    'boom lift cleaning large stone facade' => 'رافعة سلة تنظف واجهة حجرية واسعة',
    'boom lift cleaning residential exterior facade' => 'رافعة سلة تنظف واجهة خارجية لمبنى سكني',
    'boom lift cleaning large villa exterior' => 'رافعة سلة تنظف واجهة فيلا كبيرة',
    'worker cleaning exterior facade from scaffold' => 'عامل ينظف واجهة خارجية من سقالة',
    'night exterior view of a commercial building associated with cleaning work' => 'مشهد ليلي لواجهة مبنى تجاري ضمن أعمال التنظيف',
    'boom lift cleaning a multi-storey glass facade' => 'رافعة سلة تنظف واجهة زجاجية متعددة الطوابق',
    'workers cleaning decorative entrance glass and facade details' => 'عمال ينظفون زجاج مدخل زخرفيًا وتفاصيل واجهة',
    'scaffold cleaning curved tower windows' => 'سقالة لتنظيف نوافذ برج منحنية',
    'rope-access workers cleaning tall glass facade' => 'فنيون بالحبال ينظفون واجهة زجاجية مرتفعة',
    'workers cleaning blue facade panels from a boom lift' => 'عمال ينظفون ألواح واجهة زرقاء من رافعة سلة',
    'workers cleaning multi-storey exterior facade' => 'عمال ينظفون واجهة خارجية متعددة الطوابق',
    'boom-lift team cleaning modern building facade' => 'فريق على رافعة سلة ينظف واجهة مبنى حديث',
    'workers using scaffold or access structure beside exterior glazing' => 'عمال يستخدمون سقالة بجوار تزجيج خارجي',
    'worker using rotary floor machine' => 'عامل يشغّل ماكينة جلي دوّارة',
    'worker operating floor polishing or scrubbing machine' => 'عامل يشغّل ماكينة تلميع أو فرك أرضيات',
    'clean corridor flooring in newly finished residence' => 'أرضية ممر نظيفة في مسكن حديث التشطيب',
    'worker polishing a light-colored interior floor with rotary machine' => 'عامل يلمّع أرضية داخلية فاتحة بماكينة دوّارة',
    'worker operating rotary floor machine in an empty room' => 'عامل يشغّل ماكينة جلي دوّارة في غرفة فارغة',
    'exterior patterned paving showing dirt and staining before cleaning' => 'بلاط خارجي منقوش عليه اتساخ وبقع قبل التنظيف',
    'worker polishing or scrubbing an outdoor floor with a rotary machine' => 'عامل يفرك أرضية خارجية بماكينة دوّارة',
    'linear drain and floor edge being detail-cleaned' => 'قناة تصريف خطية وحافة أرضية أثناء تنظيفها بالتفصيل',
    'worker polishing indoor floor with rotary machine' => 'عامل يلمّع أرضية داخلية بماكينة دوّارة',
    'clean reflective interior floor after cleaning' => 'أرضية داخلية عاكسة نظيفة بعد التنظيف',
    'clean light-colored floor in finished interior' => 'أرضية فاتحة نظيفة في مساحة داخلية مكتملة',
    'worker pressure washing exterior wall' => 'عامل يغسل جدارًا خارجيًا بضغط الماء',
    'worker hand-cleaning floor surface near a wall' => 'عامل ينظف سطح أرضية يدويًا بجوار جدار',
    'worker performing detailed cleaning of kitchen cabinets, surfaces and appliances' => 'عامل ينظف خزائن مطبخ وأسطحه وأجهزته بالتفصيل',
    'workers cleaning a long bathroom mirror and vanity area' => 'عمال ينظفون مرآة حمام طويلة ومنطقة المغاسل',
    'workers cleaning large commercial glass panels and windows' => 'عمال ينظفون ألواح زجاج تجارية كبيرة ونوافذ',
    'worker cleaning large glass doors in a newly finished interior' => 'عامل ينظف أبوابًا زجاجية كبيرة في مساحة حديثة التشطيب',
    'worker washing tall interior glass panels' => 'عامل يغسل ألواح زجاج داخلية مرتفعة',
    'worker cleaning interior office glass' => 'عامل ينظف زجاجًا داخليًا في مكتب',
    'worker using an extension pole to clean high corridor surfaces' => 'عامل يستخدم عصا تلسكوبية لتنظيف أسطح ممر مرتفعة',
    'worker cleaning tall glass doors in a villa' => 'عامل ينظف أبوابًا زجاجية مرتفعة في فيلا',
    'worker cleaning a large glass door with a long-handled tool' => 'عامل ينظف بابًا زجاجيًا كبيرًا بأداة طويلة اليد',
    'worker cleaning exterior window and surrounding wall' => 'عامل ينظف نافذة خارجية والجدار المحيط بها',
    'worker cleaning exterior facade from elevated access' => 'عامل ينظف واجهة خارجية من وصول مرتفع',
    'worker vacuuming and wiping office desks, chairs and workstations' => 'عامل يشفط ويمسح مكاتب وكراسي ومحطات عمل',
    'worker cleaning exterior glass railing or canopy' => 'عامل ينظف درابزينًا زجاجيًا خارجيًا أو مظلة',
    'worker deep-cleaning kitchen cabinets and lower counter area' => 'عامل ينظف خزائن مطبخ ومنطقة الكاونتر السفلية تنظيفًا عميقًا',
    'large set of cushions removed and arranged during cleaning' => 'مجموعة وسائد مرفوعة ومرتبة أثناء التنظيف',
    'stone staircase after cleaning and detailing' => 'درج حجري بعد التنظيف والتفصيل',
    'team cleaning wet polished interior floor' => 'فريق ينظف أرضية داخلية لامعة مبللة',
    'workers cleaning epoxy floor' => 'عمال ينظفون أرضية إيبوكسي',
    'worker handling and cleaning a large black equipment unit' => 'عامل ينظف وحدة معدات سوداء كبيرة',
    'workers cleaning office glass and partitions' => 'عمال ينظفون زجاج مكتب وقواطعه',
    'worker cleaning landscaped grounds beside a building' => 'عامل ينظف منطقة مزروعة بجوار مبنى',
    'exterior building view related to a cleaning work site' => 'مشهد خارجي لمبنى ضمن موقع عمل تنظيف',
    'workers cleaning company yards and outdoor walkways' => 'عمال ينظفون ساحات منشأة وممرات خارجية',
    'worker cleaning decorative outdoor structure or entrance' => 'عامل ينظف عنصرًا خارجيًا زخرفيًا أو مدخلًا',
    'worker cleaning outdoor patio and furniture at a residential property' => 'عامل ينظف فناءً خارجيًا وأثاثه في عقار سكني',
    'rotary floor machine cleaning an outdoor stone or tile surface' => 'ماكينة جلي دوّارة تنظف سطحًا حجريًا أو مبلطًا خارجيًا',
    'floor polishing machine operating on exterior tiled surface' => 'ماكينة تلميع أرضيات تعمل على سطح مبلط خارجي',
    'clean tiled terrace and glass railing documented in project sequence' => 'تراس مبلط نظيف ودرابزين زجاجي ضمن توثيق المشروع',
    'workers cleaning large swimming pool' => 'عمال ينظفون مسبحًا كبيرًا',
    'long exterior walkway being washed and cleaned' => 'ممر خارجي طويل أثناء غسله وتنظيفه',
    'worker detail-cleaning bathroom floor and shower edge' => 'عامل ينظف أرضية حمام وحافة الدش بالتفصيل',
    'worker cleaning cabinet and under-counter surfaces' => 'عامل ينظف خزانة وأسطحًا أسفل الكاونتر',
    'workers cleaning outdoor paved walkway' => 'عمال ينظفون ممرًا خارجيًا مبلطًا',
    'worker manually cleaning interior floor' => 'عامل ينظف أرضية داخلية يدويًا',
    'worker cleaning wall and handrail surfaces' => 'عامل ينظف أسطح جدار ودرابزين',
    'worker cleaning a large overhead grille or ventilation detail' => 'عامل ينظف شبكة تهوية علوية كبيرة',
    'worker detail-cleaning built-in furniture, cabinets or shelving' => 'عامل ينظف أثاثًا مدمجًا وخزائن ورفوفًا بالتفصيل',
    'deep cleaning inside sports academy facility' => 'تنظيف عميق داخل أكاديمية رياضية',
    'worker cleaning floor edge and skirting in an empty room' => 'عامل ينظف حافة أرضية وقاعدة حائط في غرفة فارغة',
    'worker detail-cleaning floor and door threshold' => 'عامل ينظف أرضية وعتبة باب بالتفصيل',
    'worker detailing stair edge and floor surface' => 'عامل ينظف حافة درجة وسطح أرضية بالتفصيل',
    'workers removing construction residue from exterior flooring and entrance surfaces' => 'عمال يزيلون بقايا البناء عن أرضيات خارجية ومساحات المدخل',
    'worker cleaning patterned interior flooring' => 'عامل ينظف أرضية داخلية منقوشة',
    'worker detail-cleaning floor edge beside wall' => 'عامل ينظف حافة أرضية بجانب جدار',
    'worker mopping or sweeping a bright interior floor' => 'عامل يمسح أرضية داخلية فاتحة',
    'cleaning crew working at a commercial storefront entrance' => 'طاقم تنظيف يعمل عند مدخل واجهة محل تجاري',
    'close-up of upholstered fabric showing a visible cleaned or marked section' => 'لقطة قريبة لقماش مفروشات يظهر فيها جزء منظَّف',
    'worker cleaning tiled swimming pool' => 'عامل ينظف مسبحًا مبلطًا',
    'worker cleaning decorative exterior facade or wall' => 'عامل ينظف واجهة خارجية زخرفية أو جدارًا',
    'workers cleaning empty swimming pool surface' => 'عمال ينظفون سطح مسبح فارغ',
    'worker cleaning a sofa cushion in a residential living room' => 'عامل ينظف وسادة كنبة في صالة سكنية',
    'cleaning team working along a wide interior corridor' => 'فريق تنظيف يعمل على امتداد ممر داخلي واسع',
    'workers scrubbing tall wall surfaces with long-handled tools' => 'عمال يفركون أسطح جدران مرتفعة بأدوات طويلة اليد',
    'cleaning large interior floor area' => 'تنظيف مساحة أرضية داخلية واسعة',
    'cleaning team washing a shopping mall floor during active service work' => 'فريق تنظيف يغسل أرضية مركز تجاري أثناء الخدمة',
];
